// Generated by uniffi-bindgen-react-native
#include "my-rust-lib.h"
#include "generated/foobar.hpp"

namespace myrustlib {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeFoobar::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}